config/routes.rb
# frozen_string_literal: true

Pbs::Application.routes.draw do
  get "invitations/new"
  get "invitations/create"

  # A user should go straight to their list of subjects (people).
  # In the future that could be further optimized (maybe) to go to the subject,
  # if the user has only one subject.
  resources :users, only: %i[show edit update] do
    member do
      get "home"
    end
  end

  # TODO: completed_routines could be shallowly nested under routines.
  resources :completed_routines, except: %i[show destroy]
  resources :awards, only: %i[new create]
  resources :people do
    member do
      get "reports"
    end
    resources :goals, shallow: true, except: %i[show]
    resources :routines, shallow: true do
      member do
        get "reports"
      end
    end
  end
  resources :links, only: [:destroy]
  resources :messages, only: %i[index create new update]
  resources :invitations, only: %i[create new] do
    member do
      get "respond" # TODO: This should be put or post, but I can't test it.
    end
  end

  # You can have the root of your site routed with "root"
  root "welcome#index"

  # From: http://railscasts.com/episodes/241-simple-omniauth-revised
  # Except I had to change "match" to "get", as suggested here: https://github.com/RailsApps/rails-composer/issues/111
  get "auth/:provider/callback", to: "sessions#create"
  get "auth/failure", to: redirect("/")
  get "signout", to: "sessions#destroy", as: "signout"

  # LCR
  get "sessions/create"
  get "sessions/destroy"
  get "welcome/index"
  get "welcome/index", as: "signin"
  get "welcome/privacy"
  get "welcome/terms"
end

app/models/person.rb
# frozen_string_literal: true

class Person < ActiveRecord::Base
  belongs_to :user, optional: true # if this is an identity of a User
  belongs_to :creator, class_name: "User"
  has_many :links, foreign_key: :person_a_id
  has_many :reverse_links, foreign_key: :person_b_id, class_name: "Link"
  has_many :people, through: :links, source: :person_b
  has_many :users, through: :people, source: :user
  has_many :routines, -> { order("routines.name") }, dependent: :destroy
  has_many :completed_routines, -> { order("completed_routines.routine_done_at") }, through: :routines, dependent: :destroy
  has_many :completed_expectations, through: :completed_routines
  has_many :goals, dependent: :destroy

  has_many :pending_rewards, -> { where(pending_routines.exists?) }, class_name: "Goal"

  accepts_nested_attributes_for :routines
  accepts_nested_attributes_for :goals

  # New
  has_many :person_users, dependent: :destroy
  has_many :caregivers, through: :person_users, class_name: "User", inverse_of: :subjects, source: :user

  validates_presence_of :creator

  # rdoc
  # Return the short_name, if any, or the name.
  # The short name is intended to mask the identity of the subject,
  # so people can't learn who's under care by shoulder surfing.
  def short_name
    super || name
  end

  # rdoc
  # Link a Person to a Person or a User, bidirectionally, so that each entity is connected
  # to the other.
  # See: http://stackoverflow.com/questions/2923692/bidirectional-self-referential-associations
  # for confirmation that this is probably a good way to do it.
  def linkup(other)
    return other if other.people.any? { |p| p == self }
    retval = other
    other = other.primary_identity if other.is_a? User
    people << other
    other.people << self
    retval
  end

  # rdoc
  # Unlink a Person from another Person or a User, bidirectionally, so that each entity is disconnected
  # to the other.
  def unlink(other)
    other = other.primary_identity if other.is_a? User
    people.delete(other)
    other.people.delete(self)
  end

  # rdoc
  # Update links to the person from an array of user ids. The array contains the
  # complete list of users connected to the person.
  # I would prefer to leave them all alone, but the algorithm is harder.
  def update_team(updated_users)
    # An empty array means no users (which should happen either)
    # Nil means don't do anything with existing links.
    return if updated_users.nil?

    # Get rid of the HTML artifact.
    updated_users -= [""]

    # Don't let the app be stupid. Can't ever completely unlink a person.
    logger.warn("update_team called with an empty array.") && return if updated_users.empty?

    updated_users = updated_users.map { |u| User.find(u) }

    # Delete the links that are no longer valid.
    (users - updated_users).each do |u|
      #      puts "Unlinking: #{u.to_yaml}"
      unlink(u)
    end

    # Add the new users.
    (updated_users - users).each do |u|
      #      puts "Linking: #{u.to_yaml}"
      linkup(u)
    end

    # At the moment, no need to do anything else.
    # What happens when I put attributes on the link?
    # TODO Add parent and other atributes to links.
  end

  # rdoc
  # A person is owned by a user if:
  # * The person is the user.
  # * They're a parent of the person, # TODO
  # * If there is no parent, then the creator is the owner
  def is_owned_by?(user)
    user = User.find(user) unless user.is_a?(User)
    return true if self.user == user
    # TODO: Check for parent.
    creator == user
  end

  # rdoc
  # Get all the unique expectations, by expectation ID, for completed routines
  # for this person. These become the column headings (or row headings) for
  # the display.
  def unique_expectations
    # Select unique expectations that are in completed expectations for this person.
  end

  # rdoc
  # Get the unique dates on which this person completed at least one routine.
  def routine_dates
    completed_routines.collect { |d| d.routine_done_at.beginning_of_day }.uniq
  end

  # rdoc
  # Get arrays of the dates of completed routines and number of columns needed for each date,
  # then also grouped by month and year.
  def completed_routines_column_layout
    completed_routines
      .group_by { |cr| cr.routine_done_at.beginning_of_day }
      .collect { |k, v| [k, v.count] }
      .group_by { |x| x[0].beginning_of_month }
      .flatten

    # The date comes out as a string on sqlite and a date on MySql. Crap. Ugliness ahead.
    # More crap. Obviously I can't use a to_date-based query, since the date changes
    # based on the time zone
    #    completed_routines
    #      .group("date(completed_routines.routine_done_at)")
    #      .pluck("date(completed_routines.routine_done_at), count(*)")
    #      .collect { |x| [x[0].kind_of?(String) ? Time.find_zone('UTC').parse(x[0]).in_time_zone : x[0], x[1]]}
    #      .group_by { |x| x[0].beginning_of_month }
    #      .flatten
    # Confirm when I add time zone that this uses time zone Ha Ha. It doesn't
  end

  # rdoc
  # Get a has of routines containing completed routines grouped by date.
  def routines_layout
    Hash[
      routines
      .map do |r|
        [r, r
      .completed_routines
      .group_by { |cr| cr.routine_done_at.beginning_of_day }]
      end
    ]
  end

  def full_layout
    layout = completed_expectations.each_with_object({}) do |ce, o|
      #      puts "ce, o: #{ce}, #{o}"
      o[ce.routine] ||= {}
      o[ce.routine][ce.expectation] ||= {} # Cause we want an array next, we have to create a hash but don't return hash as default.'
      o[ce.routine][ce.expectation][ce.completed_routine.routine_done_at.beginning_of_day] ||= []
      o[ce.routine][ce.expectation][ce.completed_routine.routine_done_at.beginning_of_day] << ce
      #      puts "layout: #{o.inspect}"
    end
    layout
  end

  def completed_expectations_for_day_and_expectation(expectation, day)
    completed_expectations.find_all do |x|
      x.completed_routine.routine_done_at.beginning_of_day == day &&
        x.expectation == expectation
    end
  end
  #  def name
  #    "#{self.class}: #{super}"
  #  end
end

app/controllers/people_controller.rb
# frozen_string_literal: true

class PeopleController < ApplicationController
  before_action :user_allowed_to_modify_person, except: %i[create new]

  def edit
  end

  def new
    @person = Person.new
    @person.creator = current_user
  end

  def create
    @person = current_user.subjects.build(person_params)
    @person.caregivers << current_user

    # @person.update_team(params[:person][:users])
    if @person.save
      redirect_to person_path(@person)
    else
      render "new"
    end
  end

  def update
    @person.update_attributes(person_params)

    # @person.update_team(params[:person][:users])
    if @person.save
      redirect_to person_path(@person)
    else
      render "edit"
    end
  end

  def destroy
    @person.destroy # TODO: I don't think I want to destroy any data, so re-think this.
    redirect_back fallback_location: root_path
  end

  def show
    @completed_routines = @person.completed_routines
                                 .reorder(routine_done_at: :desc)
                                 .page(params[:page]).per(15)
  end

  def reports; end

  private

  def user_allowed_to_modify_person
    params.require(:id)
    @person = current_user.subjects.find(params[:id])
    current_user.can_modify_person?(@person) || not_found
  rescue ActiveRecord::RecordNotFound
    not_found
  end

  def person_params
    # TODO: Get rid of creator_id. Should always be current_user, and can be spoofed if it's a param.
    params.require(:person).permit(:name, :short_name, :real_name, :creator_id, caregiver_ids: [])
  end
end

app/views/people/_form.html.erb
<div id="person_edit">
  <%= bootstrap_form_for @person do |pf| %>
  <%= pf.hidden_field :creator_id %>
  <%= pf.text_field :name %>
  <%= pf.text_field :short_name,
                    help: "A name that identifies the person to anyone working with them, but won't identify the person to anyone else. This is so you don't have to worry about people identifying the person by looking over your shoulder." %>

  <%= render "routines_with_edit" %>
  <%= render "goals_with_edit" %>

  <!-- The team are users who are connected to the patient. -->
  <ul class="list-unstyled">
    <%= pf.collection_check_boxes(:caregiver_ids,
                                  (current_user.users + @person.caregivers).uniq,
                                  :id,
                                  :name,
                                  checked: @person.caregivers.map(&:id),
                                  help: "Check the boxes beside your connections that you want to allow to work with this person.",
                                  label: "Team",
                                  wrapper_class: "mt-2") do |cb| %>
    <li>
      <%= cb.check_box(disabled: current_user == cb.object) %>
      <%= hidden_field(:person, :caregiver_ids, multiple: true, value: cb.object.to_param) if current_user == cb.object %>
    </li>
  <% end %>
</ul>

<p>
  <%= link_to "Cancel", :back, class: "btn btn-secondary" %>
  <%= pf.submit 'Save' %>
</p>
<% end %>
</div>

app/views/people/_goals_with_edit.html.erb
<!-- TODO: make it so I don't have to hide this section on new. -->
<%= content_tag :div, class: "goals mt-2" do %>
  <p>Goals</p>
  <ul class="list-group">
    <% @person.goals.order(:name).each do |goal| %>
      <li class="list-group-item">
        <%= link_to edit_goal_path(goal) do %>
        <%= goal.name %>
        <%= octicon "pencil", class: "h-100 float-right" %>
      </li>
    <% end %>
  <% end %>
  <li class="list-group-item">
    <%= link_to new_person_goal_path(@person) do %>
    New Goal
    <%= octicon "plus", class: "h-100 float-right" %>
    <% end %>
    </li>
  </ul>
<% end if @person.persisted? %>

app/views/people/_pending_rewards.html.erb
<div class="pending_rewards mt-2">
  <h4>Rewards</h4>
  <% if @person.goals.pending_rewards.present? %>
  <ul class="list-group">
    <% @person.goals.pending_rewards.order(:name).each do |g| %>
    <li class="list-group-item">
      <%= link_to(new_award_path(goal_id: g.id)) do %>
      <%= g.pending %> available rewards for <%= g.name %>.
      <%= octicon "chevron-right", class: "h-100 float-right" %>
      <% end %>
    </li>
    <% end %>
  </ul>
  <% else %>
    No rewards pending.
  <% end %>
</div>

app/views/people/_routines_with_edit.html.erb
<!-- TODO: make it so I don't have to hide this section on new. -->
<%= content_tag :div, class: "routines mt-2" do %>
  <p>Routines</p>
  <ul class="list-group">
    <% @person.routines.order(:name).each do |routine| %>
      <li class="list-group-item">
        <%= link_to(routine.name, edit_routine_path(routine)) %>
        <%= octicon "pencil", class: "h-100 float-right" %>
      </li>
    <% end %>
    <li class="list-group-item">
      <%= link_to(new_person_routine_path(@person)) do %>
        New Routine
        <%= octicon "plus", class: "h-100 float-right" %>
      <% end %>
    </li>
  </ul>
<% end if @person.persisted? %>

app/views/people/_subject_dashboard.html.erb
<h1><%= patient.name %></h1>
<div class="routines content">
  <h2>Routines</h2>
  <table class="grow_child_to_parent">
    <tbody>
      <%=  patient.routines.order(:name).each do |routine| %>
      <tr>
        <td><%= link_to(routine.name, routine_path(routine)) %></td>
        <td style="text-align: right;"><%= link_to('Add New', new_completed_routine_path(routine_id: routine.id)) %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
<div class="content pending_rewards">
<h2>Rewards</h2>
  <% if 0 < patient.goals.count %>
    <table>
      <thead>
        <th>Name</th><th style="width:6em;">Target</th><th style="width:6em;">Eligible Rewards</th><th>Action</th>
      </thead>
      <tbody>
        <%=  patient.goals.order(:name).each do |g| %>
        <tr>
          <td><%= g.name %></td>
          <td style="text-align: right;"><%= g.target.to_s %></td>
          <td style="text-align: right;"><%= g.pending %></td>
          <td style="text-align: right;"><%= link_to("Give award", new_award_path(goal_id: g.id)) if g.pending > 0 %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    No goals assigned.
  <% end %>
</div>
<%= render partial: "completed_routines/completed_routines", locals: { patient: patient } %>

app/views/people/reports.html.erb
<div id="completed_routines">
  <div id="patient-name" class="container">
    <h3>Recently Completed Routines for <%= @person.name %></h3>
    <div class="completed_routines content">
      <div style="overflow:auto">
        <table>
          <thead>
            <tr>
              <th rowspan="2">Routine</th>
              <th rowspan="2">Expectation</th>
              <%= month_heading %></tr>
            <tr><%= day_heading %></tr>
          </thead>
          <tbody>
          <% @person.routines.order(name: :asc).each do |r| %>
            <%# Loop on expectations %>
            <%= r.expectations.each do |e| %>
            <tr>
              <td><%= r.name %></td>
              <td><%= e.description %></td>
              <%# Loop on Dates %>
              <% @detail_columns.each do |day, cols| %>
              <%# Loop on completed expectations within the date %>
              <% ces = @person.completed_expectations_for_day_and_expectation(e, day) %>
              <% ces.each do |ce| %>
              <td style="text-align:center"><%= ce.observation %></td>
              <% end %>
              <%# if fewer completed expectations than needed, output empty column(s) %>
              <%= (cols - ces.count).times.reduce("") { |sum, x| sum + "<td></td>"}.html_safe %>
              <% end %>
            </tr>
            <% end %>
            <% end %>
          </tbody>
        </table>
      </div>
      <!-- The following button trick doesn't work for <= IE8 -->
      <p><%= link_to '<button type="button">Back</button>'.html_safe, :back %></p>
    </div>
  </div>
</div>

app/views/people/show.html.erb
<div id="patients">
  <h4>
    <%= @person.short_name %>
    <%= link_to edit_person_path(@person), class: "btn", "aria-label": "Edit Subject", title: "Edit Subject" do %>
    <%= octicon "pencil" %>
    <% end %>
  </h4>
  <%= render partial: "routines/index" %>
  <%= render partial: "pending_rewards" %>
  <%= render partial: "completed_routines/index" %>
  <h4>
    <%= link_to "Reports", reports_person_path(@person) %>
  </h4>
</div>