config/routes.rb
# frozen_string_literal: true

Pbs::Application.routes.draw do
  get "invitations/new"
  get "invitations/create"

  # A user should go straight to their list of subjects (people).
  # In the future that could be further optimized (maybe) to go to the subject,
  # if the user has only one subject.
  resources :users, only: %i[show edit update] do
    member do
      get "home"
    end
  end

  # TODO: completed_routines could be shallowly nested under routines.
  resources :completed_routines, except: %i[show destroy]
  resources :awards, only: %i[new create]
  resources :people do
    member do
      get "reports"
    end
    resources :goals, shallow: true, except: %i[show]
    resources :routines, shallow: true do
      member do
        get "reports"
      end
    end
  end
  resources :links, only: [:destroy]
  resources :messages, only: %i[index create new update]
  resources :invitations, only: %i[create new] do
    member do
      get "respond" # TODO: This should be put or post, but I can't test it.
    end
  end

  # You can have the root of your site routed with "root"
  root "welcome#index"

  # From: http://railscasts.com/episodes/241-simple-omniauth-revised
  # Except I had to change "match" to "get", as suggested here: https://github.com/RailsApps/rails-composer/issues/111
  get "auth/:provider/callback", to: "sessions#create"
  get "auth/failure", to: redirect("/")
  get "signout", to: "sessions#destroy", as: "signout"

  # LCR
  get "sessions/create"
  get "sessions/destroy"
  get "welcome/index"
  get "welcome/index", as: "signin"
  get "welcome/privacy"
  get "welcome/terms"
end

app/models/user.rb
# frozen_string_literal: true

class User < ActiveRecord::Base
  has_many :identities, class_name: "Person", dependent: :destroy
  has_many :links, through: :identities
  has_many :people, through: :links, source: :person_b
  has_many :users, through: :people, source: :user
  has_many :messages, foreign_key: :to_id # These are received messages
  has_many :sent_messages, foreign_key: :from_id, class_name: "Message"

  # New
  has_many :person_users, dependent: :destroy
  has_many :subjects, through: :person_users, class_name: "Person", inverse_of: :caregivers, source: :person
  has_many :goals, through: :subjects
  has_many :routines, through: :subjects
  has_many :completed_routines, through: :subjects

  validate :validate_time_zone

  after_create :add_primary_identity

  # rdoc
  # Find the user based on the information provided by Omniauth,
  # or create a User based on the information provided by Omniauth if
  # it doesn't exist.
  def self.from_omniauth_or_create(auth)
    from_omniauth(auth) || create_from_omniauth(auth)
  end

  # rdoc
  # Find the user based on the information provided by Omniauth.
  def self.from_omniauth(auth)
    # where(auth.slice("provider", "uid")).first
    user = where(provider: auth["provider"], uid: auth["uid"]).first
    user.update_attributes!(email: auth["info"]["email"]) if user && user.email != auth["info"]["email"]
    user
  end

  # rdoc
  # Return true if the user already exists, based on the information
  # provided by Omniauth, false otherwise.
  def self.from_omniauth_exists?(auth)
    from_omniauth(auth) ? true : false
  end

  # rdoc
  # Create a User based on the information provided by Omniauth.
  def self.create_from_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.email = auth["info"]["email"]
      case user.provider
      when "twitter", "Training", "facebook", "yahoo"
        user.name = auth["info"]["nickname"]
      when "google_oauth2"
        user.name = auth["info"]["name"]
      else
        raise "Shouldn't happen."
      end
    end
  end

  def patients
    subjects
  end

  private

  @@providers = {
    "Google" => "google_oauth2",
    "Twitter" => "twitter",
    "Testing" => "Testing"
  }

  public

  # rdoc
  # Return hash of human readable name and internal provider name.
  def self.provider(name)
    @@providers[name]
  end

  # rdoc
  # Return of hash of internal provider name and human readable name.
  def self.inverse_provider(provider)
    @@providers.invert[provider]
  end

  # rdoc
  # Return the Person that is the primary identity of the user.
  def primary_identity
    identities.first
  end

  # rdoc
  # A user is allowed to complete a routine if they
  # can access it.
  def can_complete?(routine)
    can_access?(routine)
  end

  # rdoc
  # A user is allowed to access a routine if:
  # * they're connected to the person assigned to the routine.
  # * Possibly other conditions that are to be defined.
  def can_access?(routine)
    routine = Routine.find(routine) unless routine.is_a?(Routine)
    routine.person && team_member_for?(routine.person)
  end

  # rdoc
  # A user is allowed to access a goal if:
  # * they're connected to the person assigned to the goal.
  # * Possibly other conditions that are to be defined.
  def can_access_goal?(goal)
    goal = Routine.find(goal) unless goal.is_a?(Goal)
    return false unless goal
    people.any? { |p| p.id == goal.person_id }
  end

  # rdoc
  # Check if a user is allowed to modify an object.
  def can_modify?(o)
    case o
    when CompletedRoutine, Goal, Routine
      o.person && team_member_for?(o.person)
    else
      false
    end
  end

  # rdoc
  # Is this User on the team for the given person.
  def team_member_for?(person)
    person = Person.find(person) unless person.is_a? Person
    return false unless person
    person.caregivers.include?(self)
    # people.any? { |p| p == person }
  end

  # rdoc
  # Link a User to a Person or a User, bidirectionally, so that each entity is connected
  # to the other.
  def linkup(other)
    primary_identity.linkup(other)
  end

  # rdoc
  # Unlink a Person from another Person or a User, bidirectionally, so that each entity is disconnected
  # to the other.
  def unlink(other)
    identities.each { |i| i.unlink(other) }
  end

  # rdoc
  # Return the Link that joins one User to another.
  def link_to!(user)
    Link.find_by!(person_a: identities, person_b: user.identities)
    # This should return only one link, as the only links between two users should
    # be the forward and backward link. But I'm not so sure... Return the first for now
  end

  # rdoc
  # A user is allowed to create, modify or delete a link if:
  # * They're a participant in the link,
  # * or they created one of the participants in the link, # TODO
  # * or they're the parent of one of the participants in the link. # TODO
  def can_modify_link?(link)
    #    puts "Self: #{self.inspect}"
    #    puts "Link: #{link.inspect}"

    link = Link.find(link) unless link.is_a?(Link)
    #    puts "Person A: #{link.person_a.inspect}"
    #    puts "Person B: #{link.person_b.inspect}"
    #    puts "Answer: #{identities.any? { |i| link.person_a == i || link.person_b == i }}"

    return true if identities.any? { |i| link.person_a == i || link.person_b == i }
    false
  end

  # rdoc
  # A user is allowed to modify or delete a person if:
  # * They're the creator of the person and no parent defined for the person,
  # * or they're a parent of the person, # TODO
  # * or the person is one of the user's identities.S
  def can_modify_person?(person)
    person = Person.find(person) unless person.is_a?(Person)
    return true if person.creator == self
    identities.any? { |i| i == person } # This one has to be last or rewrite logic.
  end

  # rdoc
  # Validate the given timezone either by Rails city name or TZinfo string. Blank or nil is also okay.
  def validate_time_zone
    errors.add(:validate_time_zone, "#{time_zone} is not a valid time zone.") unless time_zone.blank? || Time.find_zone(time_zone)
  end

  # rdoc
  # Unread messages.
  def unread_messages(_requery = false)
    messages.reload.where(read: false)
  end

  # rdoc
  # Send an invitation to someone based on identity provider and name.
  # Silently do nothing if there is no user that matches.
  def send_invitation(id)
    return unless to = User.find(id)
    Message.create! do |m|
      m.from = self
      m.to = to
      m.body = "#{name} would like to connect so you can work together."
      m.message_type = "invitation"
    end
  end

  private

  # rdoc
  # After create callback to add the primary identity of the user.
  def add_primary_identity
    (identities << Person.create!(name: name, creator_id: id)).first
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :user_allowed
  before_action :validate_login
  before_action :set_user

  def show; end

  def home
    #    flash.notice = "Test notice"
    #    flash.alert = "Test alert\nline 2\nline 3\nline 4\nline 5\nline 6"
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update_attributes(user_params)
      redirect_to home_user_path(@user)
    else
      render "edit"
    end
  end

  private

  def validate_login
    not_found if current_user.nil? || current_user.id.to_s != params[:id]
  end

  def set_user
    @user = User.find(params[:id])
  end

  def user_allowed
    params[:id].nil? || current_user.id.to_s == params[:id] || not_found
  end

  def user_params
    params.require(:user).permit(:time_zone)
  end
end

app/views/users/_teams.html.erb
<ul class="list-group">
  <% @user.subjects.order(:short_name).each do | patient | %>
  <li class="list-group-item person">
    <%= link_to person_path(patient) do %>
      <%= patient.short_name %>
      <%= octicon "chevron-right", class: "h-100 float-right" %>
    <% end %>
  </li>
  <% end %>
  <li class="list-group-item">
    <%= link_to new_person_path do %>
      New Subject
      <%= octicon "plus", class: "h-100 float-right" %>
    <% end %>
  </li>
</ul>

app/views/users/edit.html.erb
<div id="user">
  <h4>Profile</h4>
  <%= bootstrap_form_for(@user) do |f| %>
  <%= f.email_field :email %>
  <%= f.time_zone_select :time_zone, ActiveSupport::TimeZone.us_zones, selected: @user.time_zone %>

  <div class="actions">
    <%= link_to "Cancel", :back, class: "btn btn-secondary" %>
    <%= f.submit "Update Profile" %>
  </div>

  <h4>Identity</h4>
  <!-- TODO: Rationalize error handling. Need something for base errors. -->
  <% if @user.errors.any? %>
  <div class="error_messages">
    <h2>Form is invalid</h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="even_row">
  <%= f.text_field :id, readonly: "readonly", label: "Unique User ID", help: "This is the information you have to send to someone else so that they can invite you to connect." %>
  </div>

  <p>
    Identity Provider:
    <%= User.inverse_provider(f.object.provider) %>
    <br/>
    Name:
    <%= f.object.name %>
  </p>
  <% end %>

  <div id="people">
    <hr>Linked People</hr>
    <table>
      <tbody>
        <% @user.users.each do |other| %>
        <tr class="user">
          <td><%= other.name %></td>
          <td><%= link_to("Unlink", link_path(@user.link_to!(other)), method: :delete, class: "btn btn-secondary btn-sm") %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <p>
      <%= link_to "Invite a User to Link Up", new_invitation_path, class: "btn btn-secondary" %>
    </p>
  </div>
</div>

app/views/users/home.html.erb
<div id="home">
  <div id="patients">
    <%= render partial: "teams" %>
  </div>
</div>

app/views/users/show.html.erb
<%# This Source Code Form is subject to the terms of the Mozilla Public
License, v. 2.0. If a copy of the MPL was not distributed with this
file, You can obtain one at http://mozilla.org/MPL/2.0/.
Copyright (c) Jade Systems Inc. 2013, 2014
%>
<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>ID:</strong>
  <%= @user.id %>
</p>
 
<p>
  <strong>Identity Provider:</strong>
  <%= @user.provider %>
</p>
 
<p>
  <strong>Identity Provider ID:</strong>
  <%= @user.uid %>
</p>