config/routes.rb
# frozen_string_literal: true

Pbs::Application.routes.draw do
  get "invitations/new"
  get "invitations/create"

  # A user should go straight to their list of subjects (people).
  # In the future that could be further optimized (maybe) to go to the subject,
  # if the user has only one subject.
  resources :users, only: %i[show edit update] do
    member do
      get "home"
    end
  end

  # TODO: completed_routines could be shallowly nested under routines.
  resources :completed_routines, except: %i[show destroy]
  resources :awards, only: %i[new create]
  resources :people do
    member do
      get "reports"
    end
    resources :goals, shallow: true, except: %i[show]
    resources :routines, shallow: true do
      member do
        get "reports"
      end
    end
  end
  resources :links, only: [:destroy]
  resources :messages, only: %i[index create new update]
  resources :invitations, only: %i[create new] do
    member do
      get "respond" # TODO: This should be put or post, but I can't test it.
    end
  end

  # You can have the root of your site routed with "root"
  root "welcome#index"

  # From: http://railscasts.com/episodes/241-simple-omniauth-revised
  # Except I had to change "match" to "get", as suggested here: https://github.com/RailsApps/rails-composer/issues/111
  get "auth/:provider/callback", to: "sessions#create"
  get "auth/failure", to: redirect("/")
  get "signout", to: "sessions#destroy", as: "signout"

  # LCR
  get "sessions/create"
  get "sessions/destroy"
  get "welcome/index"
  get "welcome/index", as: "signin"
  get "welcome/privacy"
  get "welcome/terms"
end

app/models/completed_routine.rb
# frozen_string_literal: true

class CompletedRoutine < ActiveRecord::Base
  belongs_to :person
  belongs_to :routine
  belongs_to :recorded_by, class_name: "User", optional: true
  belongs_to :updated_by, class_name: "User", optional: true
  belongs_to :routine_category, optional: true
  has_many :completed_expectations, dependent: :destroy
  accepts_nested_attributes_for :completed_expectations, allow_destroy: true
  scope :most_recent, ->(n = 10_000) { reorder(routine_done_at: :desc).limit(n) } # TODO: either remove the limit or get rid of this scope altogether
  scope :clean, -> { where_not_exists(:completed_expectations, "observation = 'N' or observation is null") }
  scope :dirty, -> { where_exists(:completed_expectations, "observation = 'N' or observation is null") }
  scope :unawarded, -> { clean.where(awarded: false) }

  before_create :set_routine_done_at

  validates_datetime :routine_done_at, allow_blank: true

  # rdoc
  # By default, the routine is given a date and time of when the person began
  # recording the observations. This field is editable in the form.
  def set_routine_done_at
    self.routine_done_at ||= Time.zone.now
  end

  # rdoc
  # Override == when the other object is a Routine, to test only the attributes
  # that make sense to compare.
  def ==(other)
    #    puts "Self is a #{self.class}. Other is a #{other.class}"
    return super unless other.is_a? Routine
    comparable_attributes == other.comparable_attributes
  end

  # rdoc
  # Return a hash of attributes that make sense to compare to a routine.
  def comparable_attributes
    attributes.slice("routine_id", "name", "person_id").merge(
      "completed_expectations_attributes" => completed_expectations.collect(&:comparable_attributes)
    )
  end

  # rdoc
  # Return true if all expectations in the routine were completed successfully,
  # or weren't able to be completed through no fault of the patient.
  def is_clean?
    completed_expectations.all?(&:is_clean?)
  end

  # rdoc
  # Return all the expectations that have ever existed for the routine associated
  # with this comopleted routine.
  def expectations
    Expectation.distinct.where(routine_id: routine_id)
  end

  # FROM http://railscasts.com/episodes/102-auto-complete-association-revised
  # rdoc
  # Return the category name for the completed routine.
  def category_name
    routine_category.try(:name)
  end

  # rdoc
  # Set the category based on the name.
  def category_name=(name)
    self.routine_category = RoutineCategory.find_or_create_by(name: name, person_id: person_id) if name.present?
  end
end

# A more general way to change keys in a hash is this
# (http://stackoverflow.com/questions/4137824/how-to-elegantly-rename-all-keys-in-a-hash-in-ruby):
#
# ages = { "Bruce" => 32, "Clark" => 28 }
# mappings = {"Bruce" => "Bruce Wayne", "Clark" => "Clark Kent"}
#
# Hash[ages.map {|k, v| [mappings[k], v] }]

app/controllers/completed_routines_controller.rb
# frozen_string_literal: true

class CompletedRoutinesController < ApplicationController
  before_action :user_allowed_to_complete_routine, only: [:new]
  before_action :user_allowed_to_edit, except: %i[new create index report]

  def new
    template = current_user.routines.find(params[:routine_id])
    #    puts template.comparable_attributes
    #    puts template.expectations.size
    @completed_routine = CompletedRoutine.new(template.copyable_attributes)
    @completed_routine.recorded_by = current_user
    #    puts @completed_routine.comparable_attributes
    #    puts @completed_routine.completed_expectations.size
    #
    #    template.expectations.each do |e|
    #      @completed_routine.completed_expectations << CompletedExpectation.new(description: e.description)
    #    end
  rescue ActiveRecord::RecordNotFound
    not_found
  end

  def create
    params[:completed_routine][:recorded_by_id] = current_user.id
    @completed_routine = CompletedRoutine.new(completed_routine_params)
    if @completed_routine.save
      redirect_to person_path(@completed_routine.person)
    else
      logger.error("Failed to create CompletedRoutine #{@completed_routine}: #{@completed_routine.errors.full_messages}")
      render "new"
    end
  end

  def edit
    # FIXME: What am I doing here???
    render "new"
  end

  def update
    params[:completed_routine][:updated_by_id] = current_user.id
    @completed_routine.update_attributes(completed_routine_params)
    if @completed_routine.save
      redirect_to person_path(@completed_routine.person)
    else
      logger.error("Failed to update CompletedRoutine #{@completed_routine}: #{@completed_routine.errors.full_messages}")
      render "new"
    end
  end

  def index
    params.require(:person_id)
    @person = current_user.subjects.find(params[:person_id])
  end

  def report; end

  private

  def user_allowed_to_complete_routine
    params.require(:routine_id) # Theoretically, this isn't right, but it seems to work.
    current_user.can_complete?(params[:routine_id]) || not_found
  end

  def user_allowed_to_edit
    @completed_routine = current_user.completed_routines.find(params[:id])
    current_user.can_modify?(@completed_routine) || not_found
  rescue ActiveRecord::RecordNotFound
    not_found
  end

  def completed_routine_params
    r = params.require(:completed_routine)
    unless params[:completed_routine][:routine_done_at]
      params[:completed_routine][:routine_done_at] =
        params[:completed_routine][:routine_done_at_date] +
        " " +
        params[:completed_routine][:routine_done_at_time]
    end
    r.permit(:id,
      :routine_id,
      :person_id,
      :category_name,
      :comment,
      :name,
      :routine_done_at,
      :recorded_by_id,
      :updated_by_id,
      completed_expectations_attributes: %i[id description observation comment])
  end
end

app/helpers/completed_routines_helper.rb
=begin
This Source Code Form is subject to the terms of the Mozilla Public
License, v. 2.0. If a copy of the MPL was not distributed with this
file, You can obtain one at http://mozilla.org/MPL/2.0/.
Copyright (c) Jade Systems Inc. 2013, 2014
=end

=begin
=end
module CompletedRoutinesHelper
  def month_heading
    @column_layout ||= @person.completed_routines_column_layout
    
#    puts @column_layout
#    puts @routines_layout
    
#    detail_columns = Hash.new(0)
#    @routines_layout.each_with_object(target) do |(date, crs), hash| 
#      crs.each_with_object(hash) do |(date, crs), hash|
##        puts "date: #{date} crs: #{crs.count} crs #{crs.inspect}"
#        hash[date] = [crs.count, hash[date]].max
#      end
#    end
    
#    puts "Target: #{target.inspect}"
    
    by_month = Hash.new(0)
    detail_columns.each_with_object(by_month) do |(date,n), by_month|
      by_month[date.beginning_of_month] += n
    end

    heading = by_month.inject("") do |memo, month|
#      puts month.inspect
      memo += "<th colspan=\"#{month[1]}\">#{month[0].strftime('%b-%Y')}</th>"
    end
    
#    puts heading
    heading.html_safe
  end
  
  def day_heading
    heading = detail_columns.inject("") do |memo, date|
      memo += "<th colspan=\"#{date[1]}\">#{date[0].strftime('%d')}</th>"
    end
#    puts heading
    heading.html_safe
  end
  
  def detail_columns
    @routines_layout ||= @person.routines_layout
    @detail_columns ||= Hash[@routines_layout.each_with_object(Hash.new(0)) do |(date, crs), hash| 
      crs.each_with_object(hash) do |(date, crs), hash|
#        puts "date: #{date} crs: #{crs.count} crs #{crs.inspect}"
        hash[date] = [crs.count, hash[date]].max
      end
    end.sort]
  end
end

app/views/completed_routines/_completed_routines.html.erb
<%# This Source Code Form is subject to the terms of the Mozilla Public
License, v. 2.0. If a copy of the MPL was not distributed with this
file, You can obtain one at http://mozilla.org/MPL/2.0/.
Copyright (c) Jade Systems Inc. 2013, 2014
%>
<div class="content completed_routines">
  <% rows_to_show = 5 %>
  <h2>Recently Completed Routines</h2>
  <% if 0 < patient.completed_routines.count %>
    <table>
      <thead>
        <th>Routine</th><th>Clean?</th><th>Date</th>
      </thead>
      <tbody>
      <%= content_tag_for(:tr, patient.completed_routines.most_recent(rows_to_show)) do |cr| %>
        <td><%= link_to(cr.name, edit_completed_routine_path(cr)) %></td>
        <td style="text-align: center;"><%= cr.is_clean?.humanize %></td>
        <td style="text-align: right;"><%= cr.routine_done_at.to_s(:humanized_ago) %></td> 
      <% end %>
      </tbody>
    </table>
    <% if rows_to_show < patient.completed_routines.size %>
      <p><%= link_to("More...", completed_routines_path(person_id: patient.id)) %></p>
    <% end %>
  <% else %>
    No recently completed routines.
  <% end %>
</div>

app/views/completed_routines/_form.html.erb
<!-- FIXME: Do the messages/flashes right. -->
<%= validation_messages @completed_routine %>

<%# The next two are to handle mobile devices. Sure wish I had my head around this better. %>
<%= yield :heading_buttons if content_for? :heading_buttons %>
<%= yield :flashes if content_for? :flashes %>

<%= bootstrap_form_for(@completed_routine) do |crf| %>
  <%= crf.hidden_field :name %>
  <%= crf.hidden_field :routine_id %>
  <%= crf.hidden_field :person_id %>
  <%= crf.fields_for(:completed_expectations, class: :expectations) do |cef| %>
    <div class="row <%= css_test_class(cef.object.description) -%> <%= "border-top pt-1" unless cef.index.zero? -%>">
      <div class="col-12 col-sm">
        <%= cef.object.description %>
        <%= cef.hidden_field :description %>
      </div>
      <div class="col-12 col-sm">
        <%= cef.form_group(:observation, layout: :inline) do %>
        <!-- Bootstrap decides that even though I said *inline*, it won't do inline on xs devices. -->
        <!-- TODO: Fix https://github.com/bootstrap-ruby/bootstrap_form/issues/476 -->
        <%= cef.radio_button :observation, "Y", label_class: "mr-2", wrapper_class: "w-auto" %>
        <%= cef.radio_button :observation, "N", label_class: "mr-2", wrapper_class: "w-auto" %>
        <%= cef.radio_button :observation, "N/A", label: "N/A", label_class: "mr-2", wrapper_class: "w-auto" %>
        <% end %>
      </div>
      <div class="col-12 col-sm">
        <%= cef.text_field(:comment, placeholder: "Comment", hide_label: true) %>
      </div>
    </div>
  <% end %>

  <div class="row mt-2">
    <div class="col-6">
      <%= crf.text_field(:category_name,
        placeholder: "Category",
        id: "completed_routine_category_name",
        data: { autocomplete_source: RoutineCategory.order(:name).map(&:name) }) %>
    </div>
    <div class="col-6">
      <% @completed_routine.routine_done_at ||= Time.zone.now %>
      <%# NOTE: According to docs I shouldn't have to give my own format, but I do. %>
      <%= crf.datetime_field :routine_done_at, value: crf.object.routine_done_at.strftime("%Y-%m-%dT%R") %>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <span class="input_fill_rest_of_line">
        <%= crf.text_field(:comment, placeholder: "Routine comment") %>
      </span>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <%= crf.text_field :recorded_by, value: crf.object.recorded_by&.name, disabled: true, label: "Recorded by" %>
    </div>
    <div class="col">
      <%= crf.text_field :updated_by, value: current_user.name, disabled: true, label: "Updated by" %>
    </div>
  </div>
  <p>
    <%= yield :cancel_button if content_for? :cancel_button %>
    <%= crf.submit 'Save' %>
  </p>
<% end %>

app/views/completed_routines/_index.html.erb
<div class="completed_routines mt-2">
  <h4>Recently Completed Routines</h4>
  <% if 0 < @completed_routines.count %>
    <table class="table">
      <thead>
        <th class="text-left">Routine</th>
        <th class="text-center">Clean?</th>
        <th class="text-right">Date</th>
      </thead>
      <tbody>
      <% @completed_routines.each do |cr| %>
        <tr class="<%= cr.is_clean? ? "clean_routine" : "dirty_routine" %>">
          <td>
            <%= link_to(cr.name, edit_completed_routine_path(cr)) %>
          </td>
          <td class="text-center"><%= cr.is_clean?.humanize %></td>
          <td class="text-right"><%= cr.routine_done_at.to_s(:humanized_ago) %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
    <%= paginate @completed_routines %>
  <% else %>
    <p>No recently completed routines.</p>
  <% end %>
</div>

app/views/completed_routines/index.html.erb
<%# This Source Code Form is subject to the terms of the Mozilla Public
License, v. 2.0. If a copy of the MPL was not distributed with this
file, You can obtain one at http://mozilla.org/MPL/2.0/.
Copyright (c) Jade Systems Inc. 2013, 2014
%>
<%= render partial: "completed_routines/completed_routines", locals: { patient: @person } %>

app/views/completed_routines/new.html.erb
<% content_for :cancel_button do %>
  <%= link_to "Cancel", person_path(@completed_routine.person), class: "btn btn-secondary" %>
<% end %>

<div class="container">
  <h4><%= "#{@completed_routine.name} -- #{@completed_routine.person.short_name}" %></h4>
  <%= render partial: "form" %>
</div>

<%# FROM http://xdsoft.net/jqplugins/datetimepicker/ %>
<%#= stylesheet_link_tag("jquery.datetimepicker", media: "all") %>
<%#= javascript_include_tag("jquery.datetimepicker") %>
<!-- <script>
  $('.datetimepicker').datetimepicker({
  step: 15,
  format: 'Y-m-d H:i'
  });

  $('.buttonset').buttonset();
</script> -->

app/views/completed_routines/report.html.erb
<%# This Source Code Form is subject to the terms of the Mozilla Public
License, v. 2.0. If a copy of the MPL was not distributed with this
file, You can obtain one at http://mozilla.org/MPL/2.0/.
Copyright (c) Jade Systems Inc. 2013, 2014
%>
<div id="completed_routines">
  <div id="patient-name" class="container">
    <h1>Recently Completed Routines for <%= @person.name %></h1>
    <div class="completed_routines content">
      <div style="overflow:auto">
        <table>
          <thead>
            <tr>
              <th rowspan="2">Routine</th>
              <th rowspan="2">Expectation</th>
              <%= month_heading %></tr>
            <tr><%= day_heading %></tr>
          </thead>
          <tbody>
          <% @person.routines.order(name: :asc).each do |r| %>
            <%# Loop on expectations %>
            <%= content_tag_for(:tr, r.expectations) do |e| %>
              <td><%= r.name %></td>
              <td><%= e.description %></td>
              <%# Loop on Dates %>
              <% @detail_columns.each do |day, cols| %>
                <%# Loop on completed expectations within the date %>
                <% ces = @person.completed_expectations_for_day_and_expectation(e, day) %>
                <% ces.each do |ce| %>
                  <td style="text-align:center"><%= ce.observation %></td>
                <% end %>
                <%# if fewer completed expectations than needed, output empty column(s) %>
                <%= (cols - ces.count).times.reduce("") { |sum, x| sum + "<td></td>"}.html_safe %>
              <% end %>
            <% end %>
          <% end %>
          </tbody>
        </table>
      </div>
      <!-- The following button trick doesn't work for <= IE8 -->
      <p><%= link_to '<button type="button">Back</button>'.html_safe, :back %></p>
    </div>
  </div>
</div>