config/routes.rb
# frozen_string_literal: true

Pbs::Application.routes.draw do
  get "invitations/new"
  get "invitations/create"

  # A user should go straight to their list of subjects (people).
  # In the future that could be further optimized (maybe) to go to the subject,
  # if the user has only one subject.
  resources :users, only: %i[show edit update] do
    member do
      get "home"
    end
  end

  # TODO: completed_routines could be shallowly nested under routines.
  resources :completed_routines, except: %i[show destroy]
  resources :awards, only: %i[new create]
  resources :people do
    member do
      get "reports"
    end
    resources :goals, shallow: true, except: %i[show]
    resources :routines, shallow: true do
      member do
        get "reports"
      end
    end
  end
  resources :links, only: [:destroy]
  resources :messages, only: %i[index create new update]
  resources :invitations, only: %i[create new] do
    member do
      get "respond" # TODO: This should be put or post, but I can't test it.
    end
  end

  # You can have the root of your site routed with "root"
  root "welcome#index"

  # From: http://railscasts.com/episodes/241-simple-omniauth-revised
  # Except I had to change "match" to "get", as suggested here: https://github.com/RailsApps/rails-composer/issues/111
  get "auth/:provider/callback", to: "sessions#create"
  get "auth/failure", to: redirect("/")
  get "signout", to: "sessions#destroy", as: "signout"

  # LCR
  get "sessions/create"
  get "sessions/destroy"
  get "welcome/index"
  get "welcome/index", as: "signin"
  get "welcome/privacy"
  get "welcome/terms"
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  def title
    "Clean Routines"
  end
  helper_method :title

  # rdoc
  # Throw a page not found exception (404).
  # Use this in controllers when you want to hide a link, e.g.
  # show a not found if an unauthorized user tries to go to the
  # admin pages.
  def not_found
    raise ActionController::RoutingError, "Not Found"
  end

  #  private

  ###### Session helpers ######

  # rdoc
  # Return the user currently logged-in.
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  rescue ActiveRecord::RecordNotFound
    logger.warn "Session terminated because user not in database (break-in attempt?)."
    log_out
    raise
  end
  helper_method :current_user

  # rdoc
  # Log in a user.
  def log_in(user)
    session[:user_id] = user.is_a?(User) ? user.id : user
  end

  # rdoc
  # Log in a user.
  def log_out
    session[:user_id] = nil
  end

  # rdoc
  # Throw a routing error if there is no logged in user.
  def require_login
    not_found unless logged_in?
  end
  before_action :require_login

  # rdoc
  # Return nil if no user is logged in.
  def logged_in?
    session[:user_id]
  end

  ###### Time zone support
  # FROM http://railscasts.com/episodes/106-time-zones-revised

  around_action :user_time_zone, if: :logged_in?

  # Set the URL to which to return after creating or updating something.
  def set_back
    session[:here_after_save] = request.headers["HTTP_REFERER"]
    # puts session[:here_after_save]
  end

  # Return the URL that started the create or update.
  def where_we_came_from_url(fallback = root_path)
    session[:here_after_save] || fallback
  end
  helper_method :where_we_came_from_url

  private

  def user_time_zone(&block)
    #    puts "user_time_zone current_user: #{current_user.inspect}"
    #    puts "user_time_zone block doesn't exist." unless block
    Time.use_zone(current_user.time_zone, &block)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  # Convert a string into something that can be used as a CSS class, when it's only
  # needed for testing, i.e., doesn't affect appearance of the page.
  def css_test_class(string)
    "test-" + string.parameterize
  end

  # From http://railscasts.com/episodes/196-nested-model-form-revised
  def link_to_add_fields(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end
    link_to(name, "#", class: "add_fields", data: { id: id, fields: fields.delete("\n") })
  end

  # TODO: Rationalize message display.
  def validation_messages(object)
    content_for :flashes do
      render partial: "flashes", locals: { object: object }
    end
    #    if object.errors.any?
    #      content_for :validation_messages do
    #        content = %[
    #         <div id="error_explanation">
    #          <h2> #{pluralize(object.errors.count, "error")} prohibited this #{object.class.name.underscore.humanize.downcase} from being saved:</h2>
    #          <ul>
    #        ]
    #          object.errors.full_messages.each do |msg|
    #            content += "<li>#{msg}</li>"
    #          end
    #        content += %[
    #          </ul>
    #        </div>
    #        ]
    #        content.html_safe
    #      end
    #    end
  end
end

app/views/application/_bottom_navigation.html.erb
<%# This Source Code Form is subject to the terms of the Mozilla Public
License, v. 2.0. If a copy of the MPL was not distributed with this
file, You can obtain one at http://mozilla.org/MPL/2.0/.
Copyright (c) Jade Systems Inc. 2013, 2014
%>
  <div class="bg-dark text-light fixed-bottom d-flex">
    <div class="container d-flex">
      <ul class="nav ml-auto">
        <li class="nav-item">
          <%= link_to "Privacy", welcome_privacy_path, class: "nav-link text-light" %>
        </li>
        <li class="nav-item">
          <%= link_to "Terms", welcome_terms_path, class: "nav-link text-light" %>
        </li>
      </ul>
    </div>
  </div>

app/views/application/_flashes.html.erb
<%# This Source Code Form is subject to the terms of the Mozilla Public
License, v. 2.0. If a copy of the MPL was not distributed with this
file, You can obtain one at http://mozilla.org/MPL/2.0/.
Copyright (c) Jade Systems Inc. 2013, 2014
%>
<% unless flash.empty? && object.errors.empty? %>
  <div id="flash_area">
    <% flash.each do |name, msg| %>
      <% if msg.is_a?(String) %>
        <%= content_tag :div, msg.html_safe, class: "flash_#{name}" %>
      <% end %>
    <% end %>

    <% if object.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(object.errors.count, "error") %> 
          prevented this 
          <%= object.class.name.underscore.humanize.downcase %> 
          from being saved:</h2>
        <ul>
          <% object.errors.full_messages.each do |msg| %>
            <li><%= msg %>.</li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>
<% end %>

app/views/application/_head.html.erb
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <%= favicon_link_tag 'gold-star.ico' %>
  <title><%= title || "Clean Routines" %></title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= action_cable_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <%# The only place this is used in views/welcome/index.html.erb. %>
  <script>
    <%= yield(:javascript) %>
  </script>
</head>

app/views/application/_menu.html.erb
<nav class="navbar navbar-expand navbar-dark bg-dark fixed-top" id="test-top-menu">
  <div class="container">
    <ul class="navbar-nav justify-content-between w-100">
      <li class="nav-item">
        <% if current_user.subjects.count == 1 %>
          <%= link_to person_path(current_user.subjects.first), class: "nav-link" do %>
            <%= octicon "home", "aria-label": "Home", class: "octicon-light align-self-center" %>
            <span class="d-none d-sm-inline-block ml-sm-1">Home</span>
          <% end %>
        <% else %>
          <%= link_to home_user_path(current_user), class: "nav-link" do %>
            <%= octicon "organization", "aria-label": "Subjects", class: "octicon-light align-self-center" %>
            <span class="d-none d-sm-inline-block ml-sm-1">Subjects</span>
          <% end %>
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to messages_path(current_user), class: "nav-link position-relative" do %>
          <%= octicon "bell", "aria-label": "Notifications", class: "octicon-light align-self-center" %>
          <%= content_tag(:span,
                          current_user.messages.count,
                          class: "messages-available messages-superscript align-self-center") unless current_user.messages.count.zero? %>
          <span class="d-none d-sm-inline-block ml-sm-1">Notifications</span>
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to edit_user_path(current_user), class: "nav-link" do %>
          <%= octicon "gear", "aria-label": "Profile", class: "octicon-light align-self-center" %>
          <span class="d-none d-sm-inline-block ml-sm-1">Profile</span>
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to signout_path, class: "nav-link" do %>
          <%= octicon "sign-out", "aria-label": "Sign out", class: "octicon-light align-self-center" %>
          <span class="d-none d-sm-inline-block ml-sm-1">Sign out</span>
        <% end %>
      </li>
    </ul>
  </div>
</nav>